HFTraderConfig:
  Account : 237477
  XWatcherIP: 127.0.0.1
  XWatcherPort: 8001
  MarketGateWay: CTPMarketGateWay
  TraderGateWay: CTPTraderGateWay
  StrategyFactory: FutureStrategyFactory
  MarketConfig: /home/xtrader/XTest/HFTraderCTP/Config/HFTrader237477.yml
  TraderConfig: /home/xtrader/XTest/HFTraderCTP/Config/HFTrader237477.yml
  BackTest: false
  BackTestDataPath: /home/xtrader/XTest/HFTraderCTP/BackTest/
  BeginDay : 20250313
  EndDay: 20250314
  DataPath: /home/xtrader/XTest/HFTraderCTP/Market
  Colo: XServer
  CPUSET: 1, 2, 3
  AutoTrade: true
  StrategyList: 
    - 
      Name: LatencyTestStrategy
      ExchangeID: CFFEX
      ConfigPath: 
      ContinuousAuctionPeriod:
                  - 09:30:00.000-11:30:00.000
                  - 13:00:00.000-15:00:00.000
      Interval: 500
      CloseTick: 10
      TickerListPath: /home/xtrader/XTest/HFTraderCTP/Config/TickerList.yml

MarketConfig:
  CallAuctionPeriod: 09:29:00.000
  ContinuousAuctionPeriod:
        - 09:30:00.000-11:30:00.000
        - 13:00:00.000-15:00:00.000
  Interval: 500
  Interface:
  LocalIP: 
  MultiCastIP:  
  LocalPort: 0
  TickerListPath: /home/xtrader/XTest/HFTraderCTP/Config/TickerList.yml
  APIErrorPath: /home/xtrader/XTest/HFTraderCTP/Config/CTPError.yml
  # CTP:FrontAddr REM: LoginID
  #Extend1: tcp://180.168.146.187:10131
  Extend1: tcp://180.168.146.187:10211
  # CTP:BrokerID  REM: PassWord
  Extend2: 9999
  # CTP: UserID   REMTCP: IP  REMUDP: ExchangeID
  Extend3: 237477
  # CTP: PassWord REMTCP: Port 
  Extend4: 123456
  Extend5: 

TraderConfig:
  Broker: SimNow
  Product: Test5
  ExchangeID: SHFE
  BusinessType: 3
  BrokerID : 9999
  Account : 237477
  Password : yyl@123#com
  AppID : simnow_client_test
  AuthCode : 0000000000000000
  QryFund: true
  CancelAll: true
  CloseToday: false
  TickerCancelLimit: 2000
  OrderLimit: 4000
  TickerListPath: /home/xtrader/XTest/HFTraderCTP/Config/TickerList.yml
  APIErrorPath: /home/xtrader/XTest/HFTraderCTP/Config/CTPError.yml
  # CTP:FrontAddr YD: YD API Config file  REM: EES Trader Lib Path
  Extend1: tcp://180.168.146.187:10201
  #Extend1: tcp://180.168.146.187:10130
  # REM: TradeServerIP
  Extend2: 
  # REM: TradeServerPort
  Extend3: 
  # REM: TradeServerUDPPort
  Extend4: 
  # REM: QueryServerIP
  Extend5: 
  # REM: QueryServerPort
  Extend6:
  # REM: QuoteServerIP
  Extend7:
  # REM: QuoteServerPort
  Extend8:
  # REM: LocalTradeIP
  Extend9:
  # REM: LocalTradeUDPPort
  Extend10: 
