TickerList:                             
  -
    TickerIndex: 0
    Ticker: IC2306
    ExchangeID: CFFEX
    PriceTick: 0.2
    
  -
    TickerIndex: 1
    Ticker: IC2307
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 2
    Ticker: IC2309
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 3
    Ticker: IC2312
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 4
    Ticker: IF2306
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 5
    Ticker: IF2307
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 6
    Ticker: IF2309
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 7
    Ticker: IF2312
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 8
    Ticker: IH2306
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 9
    Ticker: IH2307
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 10
    Ticker: IH2309
    ExchangeID: CFFEX
    PriceTick: 0.2
    
  -
    TickerIndex: 11
    Ticker: IH2312
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 12
    Ticker: IM2306
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 13
    Ticker: IM2307
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 14
    Ticker: IM2309
    ExchangeID: CFFEX
    PriceTick: 0.2
    
  -
    TickerIndex: 15
    Ticker: IM2312
    ExchangeID: CFFEX
    PriceTick: 0.2
