TickerList:                             
  -
    TickerIndex: 0
    Ticker: IC2212
    ExchangeID: CFFEX
    PriceTick: 0.2
    
  -
    TickerIndex: 1
    Ticker: IC2301
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 2
    Ticker: IC2303
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 3
    Ticker: IC2306
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 4
    Ticker: IF2212
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 5
    Ticker: IF2301
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 6
    Ticker: IF2303
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 7
    Ticker: IF2306
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 8
    Ticker: IH2212
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 9
    Ticker: IH2301
    ExchangeID: CFFEX
    PriceTick: 0.2

  -
    TickerIndex: 10
    Ticker: IH2303
    ExchangeID: CFFEX
    PriceTick: 0.2
    
  -
    TickerIndex: 11
    Ticker: IH2306
    ExchangeID: CFFEX
    PriceTick: 0.2
  -
    TickerIndex: 12
    Ticker: SH000300
    ExchangeID: SH
    PriceTick: 0.01
  -
    TickerIndex: 13
    Ticker: SH000905
    ExchangeID: SH
    PriceTick: 0.01
  -
    TickerIndex: 14
    Ticker: SH000016
    ExchangeID: SH
    PriceTick: 0.01
  -
    TickerIndex: 15
    Ticker: SH000852
    ExchangeID: SH
    PriceTick: 0.01
