TickerList:
  -
    TickerIndex: 0
    Ticker: al2504
    ExchangeID: SHFE
    PriceTick: 5.0

  -
    TickerIndex: 1
    Ticker: al2505
    ExchangeID: SHFE
    PriceTick: 5.0

  -
    TickerIndex: 2
    Ticker: al2506
    ExchangeID: SHFE
    PriceTick: 5.0

  -
    TickerIndex: 3
    Ticker: al2507
    ExchangeID: SHFE
    PriceTick: 5.0
