MarketCenterConfig:
  ServerIP: 127.0.0.1
  Port: 8001
  BusinessType: 3
  ExchangeID: SH
  ToMonitor : true
  Future: false
  TotalTick: 28801
  RecvTimeOut: 150000
  MarketServer: MarketServer
  CallAuctionPeriod: 09:29:00.000
  ContinuousAuctionPeriod:
                  - 09:30:00.000-11:30:00.000
                  - 13:00:00.000-15:00:00.000
  TickerListPath: /home/xtrader/XTest/XueQiuMarket/Config/TickerList.yml
  APIConfig: /home/xtrader/XTest/XueQiuMarket/Config/XMarketCenter.yml


CrawlerMarketSource:
  Source: XueQiu
  TimeOut: 5000
  Script: /home/xtrader/.conda/envs/Quant/bin/python /home/xtrader/XTest/XueQiuMarket/XueQiuSpider.py
