TickerList:                             
  -
    TickerIndex: 0
    Ticker: p2401
    ExchangeID: DCE
    PriceTick: 1.0
    
  -
    TickerIndex: 1
    Ticker: p2402
    ExchangeID: DCE
    PriceTick: 1.0

  -
    TickerIndex: 2
    Ticker: p2403
    ExchangeID: DCE
    PriceTick: 1.0

  -
    TickerIndex: 3
    Ticker: p2404
    ExchangeID: DCE
    PriceTick: 1.0

  -
    TickerIndex: 4
    Ticker: v2401
    ExchangeID: DCE
    PriceTick: 1.0

  -
    TickerIndex: 5
    Ticker: v2402
    ExchangeID: DCE
    PriceTick: 1.0

  -
    TickerIndex: 6
    Ticker: v2403
    ExchangeID: DCE
    PriceTick: 1.0

  -
    TickerIndex: 7
    Ticker: v2404
    ExchangeID: DCE
    PriceTick: 1.0
