MarketCenterConfig:
  ServerIP: 127.0.0.1
  Port: 8001
  BusinessType: 3
  ExchangeID: SHFE
  ToMonitor : true
  Future: true
  TotalTick: 28801
  MarketServer: MarketServer1
  RecvTimeOut: 150000
  CPUSET: -1, -1, -1
  CallAuctionPeriod: 09:29:00.000
  ContinuousAuctionPeriod:
                  - 09:30:00.000-11:30:00.000
                  - 13:00:00.000-15:00:00.000
  TickerListPath: /home/xtrader/XTest/REMMarket/Config/TickerList.yml
  APIConfig: /home/xtrader/XTest/REMMarket/Config/XMarketCenter.yml

REMMarketSource:
  Account: 3866259
  Password: 1
  FrontIP: 183.129.220.106
  FrontPort: 21006
  MultiCastIP: "" 
  MultiCastPort: 0
  LocalIP: ""
  LocalPort: 0
  TickerListPath: /home/xtrader/XTest/REMMarket/Config/TickerList.yml
