HFTraderConfig:
  Account : 00031932 
  XWatcherIP: 127.0.0.1
  XWatcherPort: 8001
  MarketGateWay: ToraL1MarketGateWay
  TraderGateWay: ToraStockTraderGateWay
  StrategyFactory: StockStrategyFactory
  MarketConfig: /home/xtrader/XTest/ToraHFTrader/Config/HFTrader00031932.yml
  TraderConfig: /home/xtrader/XTest/ToraHFTrader/Config/HFTrader00031932.yml
  BackTest: false
  BackTestDataPath: /home/xtrader/HFTrader/BackTest/
  BeginDay : 2022-08-10
  EndDay: 2022-08-12
  DataPath: /home/xtrader/Test/HFTrader/BackTest/
  Colo: XServer
  CPUSET: 1, 2, 3
  AutoTrade: true
  StrategyList: 
    - 
      Name: StockTestStrategy
      ExchangeID: SHSZ
      ConfigPath: 
      ContinuousAuctionPeriod:
                  - 09:30:00.000-11:30:00.000
                  - 13:00:00.000-15:00:00.000
      Interval: 1
      CloseTick: 240000
      TickerListPath: /home/xtrader/XTest/ToraHFTrader/Config/StockTickerList.yml

MarketConfig:
  CallAuctionPeriod: 20:59:00.000
  ContinuousAuctionPeriod:
                  - 09:30:00.000-11:30:00.000
                  - 13:00:00.000-15:00:00.000
  Interval: 1
  Interface:
  LocalIP: 
  MultiCastIP:  
  LocalPort: 0
  TickerListPath: /home/xtrader/XTest/ToraHFTrader/Config/StockTickerList.yml
  APIErrorPath: /home/xtrader/HFTrader/Config/REMError.yml
  # Tora:FrontAddr tcp://210.14.72.21:4402 
  Extend1: tcp://210.14.72.21:4402
  # InterfaceIP
  Extend2: 
  # Tora: DeriveFrontAddress
  Extend3: 
  # Tora: DeriveInterfaceIP
  Extend4: 
  # Tora: 
  Extend5:  

TraderConfig:
  Broker: Tora
  Product: Tora_1
  ExchangeID: SHSZ
  BussinessType: 1
  BrokerID : 9999
  Account : 00031932
  Password : 48744916
  AppID : client
  AuthCode : client_auth_code
  QryFund: true
  CancelAll: true
  CloseToday: true
  TickerCancelLimit: 2000
  OrderLimit: 4000
  TickerListPath: /home/xtrader/XTest/ToraHFTrader/Config/StockTickerList.yml
  APIErrorPath: /home/xtrader/HFTrader/Config/REMError.yml
  # Tora:FrontAddr 
  Extend1: tcp://210.14.72.21:4400
  # Tora: ProductInfo
  Extend2: Tora_1
  # TerminalInfo 
  Extend3: zxcv
  # 
  Extend4: 0
  # 
  Extend5: 0
  # 
  Extend6: 0
  # 
  Extend7: 0
  # 
  Extend8: 0
  # 
  Extend9:
  # 
  Extend10: 0
