XTraderConfig:
  ExchangeID: SH
  Product : OES
  Broker : OES
  BrokerID : 8888
  Account : 1888000729
  Password : 1
  BusinessType: 2
  AppID : client
  AuthCode : client_auth_code
  CloseToday: false
  ServerIP: 127.0.0.1
  Port: 8001
  OpenTime: 09:00:00.000
  CloseTime: 23:30:00.000
  QryFund: false
  CancelAll: true
  CPUSET: -1, -1
  TickerListPath: /home/xtrader/XTest/OESTrader/Config/StockTickerList.yml 
  ErrorPath: /home/xtrader/XTest/OESTrader/Config/OESError.yml
  RiskServerName: RiskServer
  OrderServerName: OrderServer
  TraderAPI: OES
  TraderAPIConfig: /home/xtrader/XTest/OESTrader/Config/OESAPIC.conf
