XTraderConfig:
  Product : REM
  Broker : REM
  BrokerID : 9999
  Account : 3866259
  Password : 1
  BusinessType: 3
  AppID : client
  AuthCode : client_auth_code
  CloseToday: false
  ServerIP: 127.0.0.1
  Port: 8001
  OpenTime: 09:00:00.000
  CloseTime: 23:30:00.000
  QryFund: true
  CancelAll: true
  RiskServerName: RiskServer
  OrderServerName: OrderServer
  TickerListPath: /home/xtrader/XTest/REMTrader/Config/TickerList.yml 
  ErrorPath: /home/xtrader/XTest/REMTrader/Config/Error.yml
  RiskServerIP: 127.0.0.1
  RiskServerPort: 8008
  TraderAPI: REM
  TraderAPIConfig: /home/xtrader/XTest/REMTrader/Config/XTrader.yml

REMConfig:
  TradeServerIP: 183.129.220.106
  TradeServerPort: 21000
  TradeServerUDPPort: 0
  QueryServerIP: 183.129.220.106
  QueryServerPort: 21001
  QuoteServerIP: 183.129.220.106
  QuoteServerPort: 21006
  LocalTradeIP: 
  LocalTradeUDPPort: 0 
  EESTraderLibPath: /home/xtrader/XTest/REMTrader/Lib/
